### ISSUE TITLE
Doesn't work on Android 7 with Google Play Music

### ISSUE THREAD

**Issue by windowz414** [amirzaidi/MaterialFX#2]
It was working on my KingRooted Android 5 phone, which had Google Play Music. But now, that I have Android 7, I Magisk rooted it but the result made me sad: Literally doesn't work on Android 7 with Google Play Music. Is there a way for me to get it work. I also have Audio Modification Library module installed.

**Comment by abdulhakam** [comment]
It might not work correctly on non-qualcomm devices.

**Comment by windowz414** [comment]
> It might not work correctly on non-qualcomm devices.

I mean the Kingrooted one was MTK and the one with Android 7 was Qualcomm (MSM8920 to be exact). But Google Play Music is long dead, and my tests with YT Music, which replaced GPM, returned good results. Thanks for the attention though!
